In [1]:
# import dependencies
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter
from matplotlib import pyplot as plt
import datetime as dt

In [3]:
from sklearn.preprocessing import LabelEncoder
from sklearn import linear_model
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
from xgboost import XGBRegressor

In [4]:
# Load the data
file_path = Path("../Resources/flight_data_clean_all.csv")
df = pd.read_csv(file_path, skiprows=0)[:-2]

df.head()

Unnamed: 0  searchDate  flightDate startingAirport destinationAirport  \
0           0  2022-09-28  2022-10-05             SFO                ORD   
1           1  2022-09-28  2022-10-05             SFO                ORD   
2           2  2022-09-28  2022-10-05             SFO                ORD   
3           3  2022-09-28  2022-10-05             SFO                PHL   
4           4  2022-09-28  2022-10-05             SFO                PHL   

    travelDuration  isBasicEconomy  isRefundable  isNonStop  totalFare  \
0  0 days 07:05:00               0             0          0     451.60   
1  0 days 07:52:00               0             0          0     451.60   
2  0 days 08:34:00               0             0          0     451.60   
3  0 days 07:49:00               0             0          0     103.99   
4  0 days 13:19:00               0             0          0     109.59   

   totalTravelDistance  searchDaysBeforeFlight  
0               1933.0                       7  
1               1933.0                       7  
2               1933.0                       7  
3               2590.0                       7  
4               2590.0                       7

In [5]:
#drop first two columns
df = df.iloc[: , 2:]
df.head()

flightDate startingAirport destinationAirport   travelDuration  \
0  2022-10-05             SFO                ORD  0 days 07:05:00   
1  2022-10-05             SFO                ORD  0 days 07:52:00   
2  2022-10-05             SFO                ORD  0 days 08:34:00   
3  2022-10-05             SFO                PHL  0 days 07:49:00   
4  2022-10-05             SFO                PHL  0 days 13:19:00   

   isBasicEconomy  isRefundable  isNonStop  totalFare  totalTravelDistance  \
0               0             0          0     451.60               1933.0   
1               0             0          0     451.60               1933.0   
2               0             0          0     451.60               1933.0   
3               0             0          0     103.99               2590.0   
4               0             0          0     109.59               2590.0   

   searchDaysBeforeFlight  
0                       7  
1                       7  
2                       7  
3                       7  
4                       7

In [6]:
#check for null values
df.isna().sum()

flightDate                     0
startingAirport                0
destinationAirport             0
travelDuration                 0
isBasicEconomy                 0
isRefundable                   0
isNonStop                      0
totalFare                      0
totalTravelDistance       116321
searchDaysBeforeFlight         0
dtype: int64

In [7]:
#drop null values. still have over 1.5 million rows of data.
df = df.dropna()
df.isna().sum()

flightDate                0
startingAirport           0
destinationAirport        0
travelDuration            0
isBasicEconomy            0
isRefundable              0
isNonStop                 0
totalFare                 0
totalTravelDistance       0
searchDaysBeforeFlight    0
dtype: int64

In [8]:
# check df datatypes
df.dtypes

flightDate                 object
startingAirport            object
destinationAirport         object
travelDuration             object
isBasicEconomy              int64
isRefundable                int64
isNonStop                   int64
totalFare                 float64
totalTravelDistance       float64
searchDaysBeforeFlight      int64
dtype: object

In [9]:
# start new df and encode startingAirport and endingAirport
le = LabelEncoder()
df2 = df.copy()
df2['startingAirport'] = le.fit_transform(df2['startingAirport'])
df2['destinationAirport'] = le.fit_transform(df2['destinationAirport'])

In [10]:
#convert travelDuration to minutes
df2['travelDurationDays'] = pd.to_numeric(df2['travelDuration'].str.slice(0,1))
df2['travelDurationHours'] = pd.to_numeric(df2['travelDuration'].str.slice(7,9))
df2['travelDurationMinutes'] = pd.to_numeric(df2['travelDuration'].str.slice(10,12))
df2['travelDurationFinal'] = ((df2['travelDurationDays']*1440)+(df2['travelDurationHours']*60)+(df2['travelDurationMinutes']))
df2 = df2.drop(columns=['travelDurationDays','travelDurationHours','travelDurationMinutes','travelDuration'])
df2.head()

flightDate  startingAirport  destinationAirport  isBasicEconomy  \
0  2022-10-05               15                  13               0   
1  2022-10-05               15                  13               0   
2  2022-10-05               15                  13               0   
3  2022-10-05               15                  14               0   
4  2022-10-05               15                  14               0   

   isRefundable  isNonStop  totalFare  totalTravelDistance  \
0             0          0     451.60               1933.0   
1             0          0     451.60               1933.0   
2             0          0     451.60               1933.0   
3             0          0     103.99               2590.0   
4             0          0     109.59               2590.0   

   searchDaysBeforeFlight  travelDurationFinal  
0                       7                  425  
1                       7                  472  
2                       7                  514  
3                       7                  469  
4                       7                  799

In [11]:
# convert flight date to number format by day of week
df2['flightDate'] = pd.to_datetime(df2['flightDate'])
s = df2['flightDate']
s = pd.Series(s)
s = s.dt.dayofweek
df2['dayOfWeek'] = s

In [12]:
df2['flightDate'] = pd.to_datetime(df2['flightDate']).astype('int64')/ 10**9

In [15]:
#check how many flights were refundable
refundable = df.loc[df["isRefundable"] == 1, :]
refundable

flightDate startingAirport destinationAirport   travelDuration  \
393695   2022-09-30             DFW                DEN  0 days 03:20:00   
399870   2022-09-30             ORD                DEN  0 days 04:30:00   
472951   2022-10-07             DFW                DEN  0 days 03:20:00   
850161   2022-10-01             DFW                DEN  0 days 03:20:00   
918542   2022-10-07             DFW                DEN  0 days 03:20:00   
1360062  2022-10-02             DFW                DEN  0 days 03:20:00   
1365556  2022-10-02             ORD                DEN  0 days 04:30:00   
1418041  2022-10-07             DFW                DEN  0 days 03:20:00   

         isBasicEconomy  isRefundable  isNonStop  totalFare  \
393695                0             1          0     472.41   
399870                0             1          0     492.41   
472951                0             1          0     422.40   
850161                0             1          0     472.41   
918542                0             1          0     422.40   
1360062               0             1          0     472.41   
1365556               0             1          0     492.41   
1418041               0             1          0     422.40   

         totalTravelDistance  searchDaysBeforeFlight  
393695                 752.0                       1  
399870                1045.0                       1  
472951                 752.0                       8  
850161                 752.0                       1  
918542                 752.0                       7  
1360062                752.0                       1  
1365556               1045.0                       1  
1418041                752.0                       6

In [16]:
#drop isRefundable column
df2 = df2.drop("isRefundable", axis=1)

In [17]:
df2.head()

flightDate  startingAirport  destinationAirport  isBasicEconomy  \
0  1.664928e+09               15                  13               0   
1  1.664928e+09               15                  13               0   
2  1.664928e+09               15                  13               0   
3  1.664928e+09               15                  14               0   
4  1.664928e+09               15                  14               0   

   isNonStop  totalFare  totalTravelDistance  searchDaysBeforeFlight  \
0          0     451.60               1933.0                       7   
1          0     451.60               1933.0                       7   
2          0     451.60               1933.0                       7   
3          0     103.99               2590.0                       7   
4          0     109.59               2590.0                       7   

   travelDurationFinal  dayOfWeek  
0                  425          2  
1                  472          2  
2                  514          2  
3                  469          2  
4                  799          2

In [18]:
df2.dtypes

flightDate                float64
startingAirport             int32
destinationAirport          int32
isBasicEconomy              int64
isNonStop                   int64
totalFare                 float64
totalTravelDistance       float64
searchDaysBeforeFlight      int64
travelDurationFinal         int64
dayOfWeek                   int64
dtype: object

In [110]:
# Creating the scaler instance
#from sklearn.preprocessing import StandardScaler
#data_scaler = StandardScaler()
#X = pd.DataFrame(data_scaler.fit_transform(df2.drop(["totalFare"],axis = 1),),columns=['flightDate','startingAirport','destinationAirport',
                                                                                      'isBasicEconomy','isRefundable','isNonStop','totalTravelDistance',
                                                                                      'searchDaysBeforeFlight','travelDurationFinal'])
#y = df2["totalFare"]

IndentationError: unexpected indent (3520715096.py, line 5)

In [111]:
#X.head()

In [19]:
# Create our features
X = df2.copy()
X = X.drop("totalFare", axis=1)

# Create our target
y = df2["totalFare"]

In [20]:
#split data into training and testing
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    random_state=1)
X_train.shape 

(1226787, 9)

In [21]:
# fit a linear regression model
regr = LinearRegression()
regr.fit(X_train, y_train) 

LinearRegression()

In [22]:
#predict flight costs
y_prediction = regr.predict(X_test)
y_prediction

array([189.74510381, 302.78720407, 321.92543527, ...,  85.94179348,
       392.28866553, 181.51038021])

In [23]:
# evaluate linear regression model
score = r2_score(y_test,y_prediction)
print('r2 score: ',score)
print('mean_sqrd_error: ',mean_squared_error(y_test,y_prediction))
print('root_mean_squared error of: ',np.sqrt(mean_squared_error(y_test,y_prediction)))

r2 score:  0.4311933866912845
mean_sqrd_error:  21270.611763539786
root_mean_squared error of:  145.8444780015335


In [27]:
#initialize random forest regressor model
X_train, y_train = make_regression(n_features=9)
forestRegr = RandomForestRegressor(max_depth=50, min_samples_split=20, n_estimators=100, random_state=0)

In [28]:
#fit random forest regessor data
forestRegr.fit(X_train, y_train)

RandomForestRegressor(max_depth=50, min_samples_split=20, random_state=0)

In [29]:
#run random forest regressor model
forestPredict = forestRegr.predict(X_test)
forestPredict

array([212.27302443, 214.77851228, 210.34697354, ..., 212.27302443,
       210.34697354, 212.27302443])

In [30]:
#evaluate random forest regressor model
forestScore = r2_score(y_test, forestPredict)
print('r2 score: ',forestScore)
print('mean_sqrd_error: ',mean_squared_error(y_test,forestPredict))
print('root_mean_squared error of: ',np.sqrt(mean_squared_error(y_test,forestPredict)))

r2 score:  -0.3258151775562159
mean_sqrd_error:  49579.06475095958
root_mean_squared error of:  222.66356853100055


In [31]:
forestRegr.feature_importances_

array([0.00335086, 0.01674276, 0.04955021, 0.05410145, 0.01681657,
       0.40216003, 0.01528036, 0.43489086, 0.0071069 ])

In [32]:
# initialize XGBRebressor
XGBR = XGBRegressor()

In [34]:
#fit XGBRegessor data
XGBR.fit(X_train, y_train)

XGBRegressor(base_score=0.5, booster='gbtree', callbacks=None,
             colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
             early_stopping_rounds=None, enable_categorical=False,
             eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
             importance_type=None, interaction_constraints='',
             learning_rate=0.300000012, max_bin=256, max_cat_to_onehot=4,
             max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
             missing=nan, monotone_constraints='()', n_estimators=100, n_jobs=0,
             num_parallel_tree=1, predictor='auto', random_state=0, reg_alpha=0,
             reg_lambda=1, ...)

In [35]:
#run XGBRegressor
XGBRPredict = XGBR.predict(X_test)

In [36]:
#evaluate XGBRegressor model
XGBRScore = r2_score(y_test, XGBRPredict)
print('r2 score: ',XGBRScore)
print('mean_sqrd_error: ',mean_squared_error(y_test,XGBRPredict))
print('root_mean_squared error of: ',np.sqrt(mean_squared_error(y_test,XGBRPredict)))

r2 score:  -0.25693276190957204
mean_sqrd_error:  47003.19610549549
root_mean_squared error of:  216.80220502913593
